ktsn/houl

- lib/cli/build.js
- lib/cli/dev.js
- lib/config.js
- test/specs/config.spec.js
If the users omit the `--config` option, houl will search the `houl.config.js` or `houl.config.json` in current working dir and its all ancestors.
> Search houl.config.js(on) if config option is not specified

- lib/cli/dev.js
- lib/externals/browser-sync.js
This `--port` (shorthand `-p`) option allows us to specify dev server's port number.
If the non-number value is specified, the command throws an error and immediately exits.
> Allow to specify dev server port

- .eslintrc.yml
- lib/cli/dev.js
- lib/dep-resolver.js
- lib/externals/browser-sync.js
- package.json
- test/specs/dep-resolver.spec.js
This feature allows the auto reloading that reflected by updating dependent files. For example, when   file A depends on file B somehow, then the user browse A and update B, the browser will be reloaded.
More concrete example:
```scss
// A.scss
@import 'B'
.foo {
color: $color;
}
```
```scss
// B.scss
$color: cyan;
```
In the above case, even if the user load only `A.scss` in her browser, the browser can be auto reloaded when she update `B.scss` because `A.scss` depends on `B.scss`.
> Resolve dependency of watched files

- lib/cli/dev.js
- lib/models/rule.js
- test/specs/models/rule.spec.js
This PR allows us to set progeny option in each item in `rules` field so that we can customize dependency resolution strategy of dev server.
See https://github.com/es128/progeny#configuration
```json
{
"input": "src",
"output": "dist",
"rules": {
"scss": {
"task": "styles",
"outputExt": "css",
"progeny": {
"rootPath": "/path/to/root"
}
}
}
}
```
> Allow to set progeny options in rules

- lib/externals/browser-sync.js
- test/specs/externals/browser-sync.spec.js
This PR is more appropriate implementation to handle omitted trailing slash.  It will redirect if the trailing slash is omitted instead of processing in the same request. 
This nullifies #13
> Redirect if trailing slash is omitted

- lib/cache-stream.js
- lib/cache.js
- lib/cli/build.js
- lib/cli/dev.js
- lib/dep-resolver.js
- lib/util.js
- package.json
- test/specs/cache-stream.spec.js
- test/specs/cache.spec.js
- test/specs/dep-resolver.spec.js
This is the first step to use a cache of previous build in `houl build`. With this feature, we can skip to transform files that does not updated from previous build including its dependencies. To use this feature, we need to specify `--cache` option with the path of cache file.
```bash
$ houl build --cache .houlcache
```
The cache file is just a json file including a hash of file and its dependencies. If `--cache` is specified, houl will load the cache file and restore the hash and dependencies, then compare them during build process.
The test cases may not fulfill all possible cases but it just works for all simple cases as far as I can see.
> Use caches in build process

- lib/cache-stream.js
- test/specs/cache-stream.spec.js
Fix #16 
This PR makes cache stream to save caches of entire files (including nested deps) in all cases. Previously, it does not save deps if the source file does not hit cache. So I've modified the strategy to resolve and save entire cache and deps after finished the cache stream.
I also noticed we don't have to compare old and new deps since if deps are updated, its contents must also be updated. I've removed relevant codes about that.
> Fix cache strategy to ensure always save all possible deps' cache

- lib/cli/build.js
- lib/models/config.js
- test/fixtures/configs/normal.config.js
- test/fixtures/configs/preset.config.js
- test/specs/models/config.spec.js
This PR stops resolving `execute` option of config file. This is not a breaking change since it just store the option in memory but does not provide any features.
We should use gulp task if we need such task that is not just build source files and output corresponding files.
> Remove execute option from config

- lib/task-stream.js
- test/specs/task-stream.spec.js
Previously, `TaskStream` module creates internal streams for each file. It probably decrease the performance for each task and cause unexpected behavior if using some plugin (like gulp-imagemin - it will print compaction stats for each file in Houl).
This patch modifies `TaskStream` to only use one stream par task and fix such behaviors.
> Refactoring task stream to use only internal stream for each rule

- lib/cache-stream.js
- lib/dep-resolver.js
- test/specs/cache-stream.spec.js
- test/specs/dep-resolver.spec.js
Fix #26 
In case some nested deps are updated, cached dep files may be refered on teardown phase of cache stream. If the cached dep files does not exist on that time, `undefined` value will be pass `progeny` and it causes file not found error.
> Avoid progeny error when root file of deps is not found

- .eslintrc.yml
- lib/config.js
- lib/models/rule.js
- lib/models/task.js
- package.json
- test/fixtures/configs/normal-with-preset-options.js
- test/fixtures/configs/preset-function.config.js
- test/fixtures/configs/preset.task.js
- test/specs/config.spec.js
- test/specs/models/rule.spec.js
We can specify some `options` for presets and tasks after merging this PR. Detailed API is in #28
> Support preset/task options

- lib/config.js
- test/fixtures/configs/no-taskfile.js
- test/specs/config.spec.js
It is valid to leave `taskFile` field empty if the user want to use preset tasks only.
> Allow an empty taskFile field in config

- lib/cli/dev.js
- lib/externals/browser-sync.js
- lib/util.js
- test/e2e/dev.spec.js
- test/specs/externals/browser-sync.spec.js
- test/specs/util.spec.js
Fix #32 
This PR adds a `--base-path` option for `dev` command. The command allows us to set the base path of the assets.
```bash
$ houl dev --base-path test
```
> Allow to set base path of dev server

- lib/externals/browser-sync.js
- lib/models/config.js
- package-lock.json
- package.json
- test/fixtures/sources/sources/index.js
- test/specs/externals/browser-sync.spec.js
- test/specs/models/config.spec.js
This PR allows us to use proxy in dev server like webpack-dev-server's proxy option.
The users may specify proxy option in thier houl config file to enable it. The proxy option is compatible with `http-proxy-middleware`'s option (in fact, houl uses `http-proxy-middleware` under the hood).
Example:
```js
module.exports = {
// ...
input: 'src',
output: 'dist',
rules: { /* ... */ },
dev: {
proxy: {
'/api': 'http://localhost:4000/api'
}
}
}
```
I ended up to put the `proxy` option under `dev` property since it would be more understandable that it only affects `dev` command. In addition, I would like to add some other options in it (`port`, `basePath` , ....)
Fix #34
> Support proxy

- README.md
- lib/models/config.js
- lib/models/rule.js
- test/specs/models/config.spec.js
- test/specs/models/rule.spec.js
We can use an array value for `exclude` option as well after merging this PR. Both `exclude` options that under the root and the `rules` can be an array.
```json
{
"input": "src",
"output": "dist",
"exclude": ["**/private/**", "**/_*"],
"rules": {
"js": {
"task": "script",
"exclude": ["**/vendor/**"]
}
}
}
```
> Allow to specify an array type for exclude option

- README.md
- bin/houl.js
- lib/cli/dev.js
- lib/cli/watch.js
- lib/externals/watcher.js
- test/e2e/build.spec.js
- test/e2e/dev.spec.js
- test/e2e/watch.spec.js
- test/expected/updated/css/index.css
- test/expected/updated/index.html
- test/expected/updated/js/index.js
- test/expected/updated/js/vendor/lib.js
- test/helpers/e2e.js
`watch` command is similar with `dev` command but it does not start dev server. It will build updated files incrementally instead.
Example:
```bash
$ houl watch -c houl.config.js
```
This command is useful in a project that requires some additional processing for asset files such as asset pipeline of Ruby on Rails.
The `watch` command can receive `--config`, `--cache` and `--dot` options similar to `build` command. I don't include `--production` flag in `watch` command intentionally since I have no idea of use case for that.
> Add watch command

- lib/cli/build.js
- lib/cli/dev.js
- lib/cli/watch.js
- lib/color.js
- lib/externals/watcher.js
- lib/loggers/build-logger.js
- lib/loggers/dev-logger.js
- lib/loggers/watch-logger.js
- lib/models/config.js
- lib/task-stream.js
- lib/util.js
- test/e2e/build.spec.js
- test/e2e/dev.spec.js
- test/e2e/watch.spec.js
- test/specs/loggers/build-logger.spec.js
- test/specs/loggers/dev-logger.spec.js
- test/specs/loggers/watch-logger.spec.js
This patch allows to print some logs while executing houl commands.
Note that this does not handle errors. It still print unhandled error event error. We may need to patch `.pipe` method and handle all error events in the user-created streams.
> feat: print log while executing build, dev or watch command

- lib/cli/watch.js
- test/fixtures/e2e/houl.config.json
- test/fixtures/e2e/src/js/_excluded.js
- test/fixtures/e2e/updated-src/js/_excluded.js
The problem that this PR addresses is that the updated files are always built even if they matches `exclude` option glob pattern.
> fix: filter updated files with `exclude` glob pattern

- lib/cli/dev.js
- lib/externals/browser-sync.js
- lib/models/config.js
- test/specs/externals/browser-sync.spec.js
- test/specs/models/config.spec.js
This PR allows the users to specify `port` and `basePath` in the config file in addition to on cli interface.
Example:
```js
module.exports = {
input: 'src',
output: 'dist',
rules: {},
dev: {
port: 51234,
basePath: '/path/to/base'
}
}
```
> feat(config): allow to specify `port` and `basePath` options under `dev`

- lib/models/config.js
- lib/util.js
- test/specs/models/config.spec.js
- test/specs/util.spec.js
This is related with #60.
If we specify `port` or `basePath` in config file, it should not be overwritten with undefined cli options. But the current behavior is like so.
This PR fix the behavior - if the cli options are not specified, it will not overwrite the options from a config file.
> fix(config): disallow overriding a config with `null` or `undefined`

- lib/cli/dev.js
The new version delete default port number.
So that the log will show:
```
Houl dev server is running at:
Local: http://localhost:undefined
External: http://192.168.188.177:undefined
```
Maybe add Integration Testing is a good choice for avoid the situation.
> log show port number

- lib/api.js
- lib/build.js
- lib/cli/build.js
- lib/cli/dev.js
- lib/cli/watch.js
- lib/config.js
- lib/dev.js
- lib/watch.js
- test/e2e/build.spec.js
- test/specs/config.spec.js
I've expose the top level tasks (`build`, `dev` and `watch`) as Node.js API. So the users can use them by importing corresponding function from `houl` package.
For example:
```js
const { build, startDevServer, watch } = require('houl')
const configPath = 'path/to/houl.config.json'
// same as `houl build`
build({ config: configPath }).then(() => {
// called after build is finished
})
// same as `houl dev`
startDevServer({ config: configPath })
// same as `houl watch`
const watcher = watch({ config: configPath })
// the returned value of watch is a chokidar watcher object
watcher.on('change', file => {
// do something
})
```
This is helpful when the users want to construct their own automation with houl.
> feat: expose top level tasks as Node.js API

- lib/externals/watcher.js
- package.json
I'm still not sure why this causes but we can avoid by setting `useFsEvents = false` on chokidar according to https://github.com/paulmillr/chokidar/issues/612
> chore(e2e): fix the problem that e2e test clashes sometimes

- lib/models/config.js
- lib/models/rule.js
- test/specs/models/config.spec.js
- test/specs/models/rule.spec.js
BREAKING CHANGE: User defined rules no longer replace preset rule. It will be merged instead.
ref #71 
For the first step, I've changed the behavior of user defined `rules` field - it will be merged with preset's `rules` fields now.
> feat: merge rules fields with preset

- lib/config.js
- lib/models/config.js
- lib/util.js
- test/fixtures/configs/normal-with-preset-modify.js
- test/specs/config.spec.js
ref #71
We can modify a preset config object by specifying `modifyConfig` function in `preset` field.
```js
module.exports = {
preset: {
name: 'foo-preset',
modifyConfig: config => {
// remove js config
delete config.rules.js
}
}
}
```
Also I made `rules` field can accept `null` or `undefined` value for the users can remove preset rules by just assigning such values.
> feat: allow to modify raw preset config
